### ISSUE TITLE
missing required module CHTTPParser on Xcode 8.3.3 

### ISSUE THREAD

**Issue by Emacos84** [IBM-Swift/Kitura-HelloWorld-iOS#11]
on 
Xcode 8.3.3 (8E3004b)
MacOS Sierra 10.12.4
DEPLOYMENT_TARGET 10.3
iphone simulator : 6s

I follow quick instructions, but when I build ClientSide, I get Swift  compile error:
<unknown>:0: error: missing required module 'CHTTPParser'

also follow: https://github.com/IBM-Swift/Kitura-HelloWorld-iOS/commit/de48561b55799998fc1456d65578e8dbacb2c1df
but it is the same.
Thanks!

![stamp1](https://user-images.githubusercontent.com/30182640/28222964-d7641a70-68c9-11e7-8f51-e52a8e740cf2.png)

**Comment by vadimeisenbergibm** [comment]
@Emacos84 Fixed, based on your solution. The PR https://github.com/IBM-Swift/Kitura-Builder-iOS/pull/1. Thanks a lot for your help!

**Comment by vadimeisenbergibm** [comment]
Just remove Builder directory and rerun make.
