### ISSUE TITLE
Improving README.md

### ISSUE THREAD

**Issue by MaisaMilena** [IBM-Swift/Kitura-HelloWorld-iOS#14]
## Description
The Prerequisites seems useless. I tried following it to configure but nothing worked properly here. 
Also, the link to Enable Server-Side Swift with Kitura doesn't work =(

## Suggestion
After failing the configuration described in Prerequisites, I delete the project and tried only the **Quick Instruction - Setup (run in a terminal)** it has the same results as Prerequisites, but it's much easier to execute (just copy all the code and paste on terminal).  
*Ps: I had the same problem and could not execute the project hahaha*

My suggestion is to delete Prerequisites and put Quick Instructions on the top of the page.

Ps: if you agree with my suggestion about removing the Prerequisites can I update it with a PR? I'm working on my Hacktoberfest progress. If there is any other suggestion that I can work on, just let me know.

**Comment by vadimeisenbergibm** [comment]
@MaisaMilena I have updated README according to your suggestion, thanks!
