### ISSUE TITLE
Doesn't load on iPhone

### ISSUE THREAD

**Issue by apistachio** [IBM-Swift/Kitura-HelloWorld-iOS#5]
The instructions seem redundant.  I followed them both (one under "building under Xcode and one under Quick Instructions"). 
Let's say one follows Quick Instructions. All versions are matching.

The problem: 3 curl 'issues' - two are "__curl_rule_01__ declared as an array with negative size" and one says could not build Objective-C module CCurl.

Since I am new to the project, I am not sure where to begin investigation or ways to resolve. 

Would it make sense to put the entire build under swift_package process and do way with shell scripts?
----
I will add, "targeting the simulator deploys as designed - it works". The problem appears when targeting a physical phone. I don't have trouble targeting this test phone with other apps - and its odd that the link fails. I also tried downloading CCurl and pushing the binary library into the right system folder (using suggested build instructions) - that didn't help here.

**Comment by vadimeisenbergibm** [comment]
@apistachio could you please let me know the version of your iPhone and iOS?

Regarding:
> Would it make sense to put the entire build under swift_package process and do way with shell scripts?

You mean the compiled curl? This way we would have to support various versions of curl and handle the license issues of curl. Anyway, you may want to fork this repository and put your compiled curl library for yourself - it is up to you which artifacts you decide to put in your source control, it is a matter of preference. This project is just an example of how one would create a Kitura/iOS server.

**Comment by apistachio** [comment]
My phone: iPhone 5 with 10.2.1

**Comment by vadimeisenbergibm** [comment]
@apistachio I see, we did not test it with iPhone 5. Let me check it next week.

**Comment by vadimeisenbergibm** [comment]
@apistachio I have received iPhone 5, will check it on Thursday. The issue is probably related to iPhone 5  being 32-bit.

**Comment by vadimeisenbergibm** [comment]
@apistachio Please perform `git pull` to get the updates, remove the `Builder` directory and run `make openXcode32`. The issue is that iPhone 5 is 32 bit, so the 32 bit version of curl has to be used.

**Comment by shanecowherd** [comment]
Confirmed Fixed when using `make openXcode32`
