### ISSUE TITLE
Unable to compile with Xcode 8.3.1

### ISSUE THREAD

**Issue by shanecowherd** [IBM-Swift/Kitura-HelloWorld-iOS#6]
macOS 10.12.4
Xcode 8.3.1

After running quick instructions.

Swift Compiler Error
KituraTableViewController.swift - `Module file's minimum deployment target is ios10.3.`

After changing the deployment target to 10.3.

Swift Compiler Error
```<unknown>:0: error: missing required modules: 'CCurl', 'CHTTPParser'```

I have tried recompiling Curl with Min version 10.3.
I have tried looking at header paths.

Is this something upstream in KituraNet?

Thanks!

**Comment by vadimeisenbergibm** [comment]
@shanecowherd and what is the device/simulator you build the app for?

**Comment by shanecowherd** [comment]
10.3
64Bit iPhone 7 Plus
64Bit iPhone 7
64Bit iPad Air 2

**Comment by shanecowherd** [comment]
<img width="880" alt="screen shot 2017-04-15 at 1 37 58 am" src="https://cloud.githubusercontent.com/assets/442439/25061836/34425abc-217c-11e7-831e-d464a6a0861b.png">

<img width="881" alt="screen shot 2017-04-15 at 1 37 28 am" src="https://cloud.githubusercontent.com/assets/442439/25061838/3b286650-217c-11e7-8152-147ef4c88058.png">

**Comment by vadimeisenbergibm** [comment]
@shanecowherd OK, I see, let me handle this on Tuesday.

**Comment by isbcd** [comment]
Xcode 8.3.2 have same problem

**Comment by vadimeisenbergibm** [comment]
@shanecowherd sorry for the long time it took us to fix it. @rodedz fixed it in https://github.com/IBM-Swift/Kitura-HelloWorld-iOS/commit/de48561b55799998fc1456d65578e8dbacb2c1df, please remove `ServerSide` and rerun `make`

@isbcd, you can try the fix with Xcode 8.3.2, I will install it and try also.

**Comment by vadimeisenbergibm** [comment]
@isbcd actually, I checked with Xcode 8.3.2, works for me with the fixes in https://github.com/IBM-Swift/Kitura-HelloWorld-iOS/issues/6#issuecomment-297399778.

**Comment by shanecowherd** [comment]
Thank you @rodedz and @vadimeisenbergibm 

Confirmed Fixed.  I was wondering if this was because of the changes to Swift Package Manager in Swift 3.1.

**Comment by isbcd** [comment]
@vadimeisenbergibm
It works. Thank you.

**Comment by vadimeisenbergibm** [comment]
@shanecowherd I think the changes by @rodedz were to update the target of the client side to 10.3,  to fix the include paths of the client project to work with the new Swift Package Manager layout (the dependencies are now in `.build/checkouts` and not in `Packages` directory).

And also to fix the ServerSide part to compile with Swift 3.1, including updating dependency versions, so dependencies also compile with Swift 3.1

**Comment by habibmohammadidev** [comment]
same error  still exist for me 
`missing required module 'CHTTPParser'`
i do all instruction listed in README with success and xcode workspace opened at the end in building process ,  i've got the above error
xcode :Version 8.3.3 (8E3004b)

**Comment by vadimeisenbergibm** [comment]
@hamedmohammadi Fixed in the issue https://github.com/IBM-Swift/Kitura-HelloWorld-iOS/issues/11 . Just remove your Builder directory, and rerun make.

**Comment by svenyonson** [comment]
Similar problem - I am trying to build for 10.3. I set this in the build settings for ClientSide and SharedServerClient - but SharedServerClient  fails saying Kitura minimum deployment target is 11.02. How can I change this and rebuild?

**Comment by vadimeisenbergibm** [comment]
@svenyonson You can specify the deployment target at this line https://github.com/IBM-Swift/Kitura-HelloWorld-iOS/blob/master/Makefile#L24:
```
DEPLOYMENT_OS=11.2
```

You can also change SIMULATOR_OS and DEVICE to be able to run tests in the command line, using `make test`.
