### ISSUE TITLE
Module file was created for incompatible target x86_64-apple-macosx10.10 error while compiling

### ISSUE THREAD

**Issue by sangy05** [IBM-Swift/Kitura-HelloWorld-iOS#8]
I tried to modify the existing server and made sure that it uses the static CURL lib . But I always get tis error . I tried all possible combination , but didnt help.

**Comment by vadimeisenbergibm** [comment]
@sangy05 Let me check it on Friday, I will not be able to get it before Friday.

**Comment by vadimeisenbergibm** [comment]
@sangy05 still did not got to handle it, sorry. Will handle it next week, currently at WWDC.

**Comment by sangy05** [comment]
No worries. I fixed it. I created the xcode proj for server side and build it once in xcode. that was the issue. It works fine, if I don't build it with xcode.
