### ISSUE TITLE
Getting this error on Xcode 8.3.2

### ISSUE THREAD

**Issue by pragnesh-is** [IBM-Swift/Kitura-HelloWorld-iOS#9]
![error](https://cloud.githubusercontent.com/assets/23501025/26827123/722fc9c8-4ad9-11e7-908e-16d033089b60.png)

Note: I have modified this file: fix_xcode_project.rb at line no: 78,
updated line is:     server_project.products.each {|p| frameworks_to_add_references.push(p) if **(p.path) &&** (p.path.include? 'framework')}, i was getting error without modifying this error

**Comment by vadimeisenbergibm** [comment]
@pragnesh-infostretch let me handle it next week, currently at WWDC

**Comment by pragnesh-is** [comment]
Ignore this, I am able to run it now.
